#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "readflow"
name = "Readflow"
description.en = " Track your Kobo reads on Anilist.co and Hardcover.app using Calibre-Web and Calibre databases "
version = "0.2.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MPL-2.0"
code = "https://github.com/RobBrazier/readflow"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = [ "amd64", "arm64" ]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.targets]
    ask.en = "Which services do you want to target?"
    type = "select"
    choices = ["anilist,hardcover", "hardcover", "anilist"]
    default = "anilist,hardcover"
    optional = true

    [install.database_calibre]
    ask.en = "Path to your Calibre metadata.db"
    type = "path"
 
    [install.database_calibreweb]
    ask.en = "Path to your Calibre-Web app.db"
    help.en = "Normally, it should be /var/www/calibreweb/app.db"
    default = "/var/www/calibreweb/app.db"
    type = "path"

    [install.token_anilist]
    ask.en = "What’s your Anilist token?"
    type = "string"
    optional = true
 
    [install.token_hardcover]
    ask.en = "What’s your Hardcover.app token?"
    type = "string"
    optional = true

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/RobBrazier/readflow/releases/download/0.3.0/readflow_0.3.0_linux_amd64"
    amd64.sha256 = "a0c2e605583afaad4257cdf73e5d15c99a42c49302e4c21bc2bad75198b43a92"

    arm64.url = "https://github.com/RobBrazier/readflow/releases/download/0.3.0/readflow_0.3.0_linux_arm64"
    arm64.sha256 = "d6650cbfcf3dc572cba98e8079ae00ed9e250dcecc202870d0335fd43e09cbca"

    extract = false
    rename = "readflow"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*amd64$"
    autoupdate.asset.arm64 = ".*arm64$"

    [resources.system_user]

    [resources.install_dir]
