#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.database_calibre = "/home/yunohost.multimedia/share/eBook/metadata.db"
    args.database_calibreweb = "/var/www/calibreweb/app.db"
    args.token_anilist = "123456789bépoè"
    args.token_hardcover = "123456789bépoè"
