#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app": "$install_dir"

#=================================================
# BUILDING SOURCES AND SETTING UP THE SERVER
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_hide_warnings ynh_go_install
	export GOPATH="$install_dir/build/go"
	export GOCACHE="$install_dir/build/.cache"

go install github.com/RobBrazier/readflow@latest

ynh_go_remove
ynh_safe_rm "$install_dir/build"
ynh_safe_rm "$install_dir/.cache"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# ADD A CRON JOB
#=================================================

ynh_config_add --template="readflow.cron" --destination="/etc/cron.d/$app"
chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
